services:
  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - postgresnetwork
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: srijan_db
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: srijan_db
    volumes:
      - .postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    networks:
      - postgresnetwork
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 
      PGADMIN_DEFAULT_PASSWORD: 
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
networks:
  postgresnetwork:
    name: postgresnetwork
    driver: bridge